name: appscanner
description: Flutter Application to find chinese app installed in phone and give thier alternatives.
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_apps: ^1.0.9
  flutter_spinkit: "^4.1.2"
  android_intent: ^0.3.7+2
  screenshot: ^0.2.0
  path_provider: ^1.6.11
  native_screenshot: ^0.0.4
  flutter_share: ^1.0.2+1
  firebase_analytics: ^5.0.14
  firebase_dynamic_links: ^0.5.1

  cupertino_icons: ^0.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/img/


  fonts:
    - family: Quicksand
      fonts:
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-Bold.ttf
        - asset: assets/fonts/Quicksand-Medium.ttf
        - asset: assets/fonts/Quicksand-Regular.ttf
        - asset: assets/fonts/Quicksand-SemiBold.ttf
          weight: 500
